version: 2.1

jobs:
  build-and-test:
  
    docker:
      - image: cimg/node:16.18

    working_directory: /circleci/home/project/frontend

    steps:
      - checkout:
        path: ~/circleci/home/project
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test

workflows:
  build-and-test:
    jobs:
      - build-and-test
